.github/workflows/ci-extension.yml
.github/workflows/ci.yml
.github/workflows/deploy-extension-dev.yml
.github/workflows/deploy-extension-prod.yml
.github/workflows/deploy-reearth-dev.yml
.github/workflows/deploy-reearth-prod.yml

Added deployment flow for built-in plugin.

ci(extension): setup deployment

---

extension/.env.example
extension/.gitignore
extension/codegen.ts
extension/package.json
extension/src/prototypes/view/ui-containers/CameraButtons.tsx
extension/src/prototypes/view/ui-containers/MainMenuButton.tsx
extension/src/shared/constants/api.ts
extension/src/shared/constants/index.ts
extension/src/shared/context/WidgetContext.tsx
extension/src/shared/graphql/base/__gen__/fragmentMatcher.json
extension/src/shared/graphql/base/__gen__/gql.ts
extension/src/shared/graphql/base/__gen__/graphql.ts
extension/src/shared/graphql/base/__gen__/index.ts
extension/src/shared/graphql/base/queries/health.ts
extension/src/shared/graphql/client.ts
extension/src/shared/graphql/hooks/base.ts
extension/src/shared/graphql/hooks/health.ts
extension/src/shared/graphql/hooks/helth.ts
extension/src/shared/graphql/hooks/index.ts
extension/src/shared/graphql/index.ts
extension/src/toolbar/Widget.tsx
extension/vite.config.ts
extension/yarn.lock
geo/.env.example
geo/.gitignore
geo/package.json
geo/src/app.module.ts
geo/src/main.ts
geo/yarn.lock

You can create new GraphQL query as follows.
1. Define a query in `/shared/graphql/base/queries` like `health.ts`
2. Run `yarn gql`, then the type for the query is generated.
3. Define hooks for the query like `/shared/graphql/hooks/health.ts`.
I will set up infrastructure for CORS.

feat(extension): add basic apollo-client

---

extension/src/prototypes/layers/LayersRenderer.tsx
extension/src/prototypes/screen-space-selection/Marquee.tsx
extension/src/prototypes/screen-space-selection/ScreenSpaceSelection.tsx
extension/src/prototypes/screen-space-selection/ScreenSpaceSelectionEvent.ts
extension/src/prototypes/screen-space-selection/ScreenSpaceSelectionHandler.ts
extension/src/prototypes/view-layers/states.ts
extension/src/prototypes/view/selection/TileFeaturePropertiesSection.tsx
extension/src/shared/layerContainers/3dtiles.tsx
extension/src/shared/layerContainers/hooks/useEvaluateFeatureColor.ts
extension/src/shared/plateau/layers/TilesetFeatureIndex.ts
extension/src/shared/plateau/utils.ts
extension/src/shared/reearth/layers/3dtiles.ts
extension/src/shared/reearth/types/appearance.ts
extension/src/shared/reearth/types/layer.ts
extension/src/shared/reearth/types/scene.ts
extension/src/toolbar/Widget.tsx
extension/src/toolbar/hooks/useAttachScreenSpaceSelection.tsx

This PR needs https://github.com/reearth/reearth/pull/716.
Added multi feature selection API.
You can test as follows.
1. Select features with mouse down and move. Then features are selected.
2. Select single feature with click. Then previous selected feature are unselected, and new one is selected.
3. Click base-map. Then features are unselectred.

feat(extension): add multi feature selection

---

extension/src/prototypes/view/hooks/useSearchOptions.ts
extension/src/prototypes/view/ui-containers/SearchAutocompletePanel.tsx
extension/src/shared/reearth/layers/3dtiles.ts
extension/src/shared/reearth/types/layer.ts

This needs https://github.com/reearth/reearth/pull/731.
- Added a basic building search feature.
- fly to selected feature(Need to use coordinates which are embedded in feature's property, but 2022's data doesn't have them, so I asked it to baba-san)

feat(extension): building search

---

extension/src/prototypes/datasets/atomsWithQuantitativeColorMap.ts
extension/src/prototypes/ui-components/ColorMapParameterItem.tsx
extension/src/shared/layerContainers/hooks/useEvaluateFeatureColor.ts
extension/src/shared/view-layers/3dtiles/createPlateauTilesetLayerState.ts
extension/src/shared/view-layers/component.ts

Color map caused some error when restore color map from local storage. I fixed this issue.

fix(extension): restore color map

---

extension/.env.example
extension/reearth-yml.ts
extension/src/shared/context/WidgetContext.tsx
extension/src/shared/graphql/client.ts
extension/src/shared/graphql/index.ts
extension/src/shared/types/widget.ts
extension/src/toolbar/Widget.tsx

fix(extension): get API from widget property

---

extension/src/editor/containers/common/commonTemplate/TemplateAddButton.tsx
extension/src/editor/containers/common/commonTemplate/TemplateHeader.tsx
extension/src/editor/containers/component-template/index.tsx
extension/src/editor/containers/dataset/blocks/FeatureInspectorEmphasisPropertyBlock.tsx
extension/src/editor/containers/dataset/blocks/FieldComponentTemplateBlock.tsx
extension/src/editor/containers/emphasis-property-template/index.tsx
extension/src/editor/containers/ui-components/editor/EditorPanel.tsx
extension/src/editor/containers/ui-components/editor/EditorTree.tsx
extension/src/editor/containers/ui-components/editor/EditorTreeItem.tsx
extension/src/editor/containers/utils.ts
extension/src/shared/api/hooks/template.ts
extension/src/shared/api/types/component.ts
extension/src/shared/states/template.ts
extension/src/shared/view/containers/InitialLayers.tsx
extension/src/toolbar/containers/InitializeApp.tsx

This PR adds UI/UX & connect API for editor templates (component template section & emphasis property template section).

feat(extension): basic editor (Part.3)

---

extension/src/prototypes/ui-components/ColorSetIcon.tsx
extension/src/prototypes/ui-components/QualitativeColorLegend.tsx
extension/src/prototypes/view/hooks/useSearchOptions.ts
extension/src/prototypes/view/ui-containers/BuildingDatasetButtonSelect.tsx
extension/src/prototypes/view/ui-containers/DatasetDialog.tsx
extension/src/prototypes/view/ui-containers/DatasetListItem.tsx
extension/src/prototypes/view/ui-containers/DefaultDatasetButton.tsx
extension/src/prototypes/view/ui-containers/DefaultDatasetSelect.tsx
extension/src/shared/states/rootLayer.ts
extension/src/shared/states/template.ts
extension/src/shared/view-layers/rootLayer.ts
extension/src/shared/view/containers/InitialLayers.tsx

I added a support of template for viewer.

feat(extension): support template for viewer

---

extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointFillColorValueField.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/base.ts
extension/src/shared/types/fieldComponents/colorScheme.ts
extension/src/shared/types/fieldComponents/point.ts
extension/src/shared/view-layers/componentField.ts
extension/src/shared/view/selection/ColorSchemeSectionForComponentField.tsx
extension/src/shared/view/state/colorSchemeForComponent.ts

- Added PointFillColorValueField
- Support legend for it
You can test it in `公園情報（札幌市）`

feat(extension): add point color value field

---

extension/package.json
extension/src/editor/containers/common/fieldComponentEditor/fields/general/EditorStyleCodeField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/editor/containers/ui-components/component/ComponentSelector.tsx
extension/src/editor/containers/ui-components/property/PropertyWrapper.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/yarn.lock

This PR adds general style code field component and use it in genreal layer.

feat(extension): add style code field

---

extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetBuildingModelColorField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/general/EditorOpacityField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/editor/containers/ui-components/property/PropertyInfo.tsx
extension/src/editor/containers/ui-components/property/PropertyNoSettings.tsx
extension/src/editor/containers/ui-components/property/index.ts
extension/src/prototypes/view/selection/BuildingLayerColorSection.tsx
extension/src/prototypes/view/selection/LayerContent.tsx
extension/src/shared/types/fieldComponents/3dtiles.ts
extension/src/shared/types/fieldComponents/index.ts
extension/src/shared/view-layers/componentField.ts
extension/src/shared/view/fields/Fields.tsx
extension/src/shared/view/fields/fieldSettings.ts

I added color component field for Plateau building model.

feat(extension): support color field for building model

---

extension/src/editor/containers/common/fieldComponentEditor/ComponentItem.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointFillColorConditionField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointFillColorValueField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointSizeField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointStyleField.tsx
extension/src/editor/containers/ui-components/property/PropertyCard.tsx
extension/src/editor/containers/ui-components/property/PropertyInputField.tsx
extension/src/editor/containers/ui-components/property/PropertySelectField.tsx
extension/src/editor/containers/ui-components/property/PropertySwitchField.tsx
extension/src/editor/containers/ui-components/property/PropertyWrapper.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/point.ts
extension/src/shared/view-layers/componentField.ts
extension/src/shared/view/fields/fieldSettings.ts

This PR:
- Adds point style component
- Adds editor UI for point size component
- Refactor some on component title / common components / etc.

feat(extension): add point style component

---

extension/src/prototypes/view/selection/LayerContent.tsx
extension/src/prototypes/view/ui-containers/SelectionPanel.tsx
extension/src/shared/layerContainers/general.tsx
extension/src/shared/reearth/layers/general.ts
extension/src/shared/reearth/types/index.ts
extension/src/shared/reearth/utils/camera.ts
extension/src/shared/states/rootLayer.ts
extension/src/shared/view-layers/general/GeneralDatasetLayer.tsx
extension/src/shared/view-layers/rootLayer.ts

- Attach the general settings in Viewer.
- General setting for layer inspector

fix(extension): use general setting in viewer

---

extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointVisibilityFilterField.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/colorScheme.ts
extension/src/shared/types/fieldComponents/point.ts
extension/src/shared/view/fields/Fields.tsx
extension/src/shared/view/fields/fieldSettings.ts
extension/src/shared/view/fields/point/LayerPointVisibilityFilterField.tsx
extension/src/shared/view/state/colorSchemeForComponent.ts

- Add visibility filter field
- You can test it with `ランドマーク情報（青葉区）` dataset

feat(extension): add visibility filter field

---

extension/src/shared/view-layers/componentField.ts
extension/src/shared/view/fields/fieldSettings.ts

I did refactor to use `fieldSettings` for ui value.

refactor(extension): use fieldSettings for ui value

---

extension/src/shared/view/fields/general/LayerOpacityField.tsx

I fixed opacity field to consider multiple layer selection.

fix(extension): opacity field for multiple selection layer content

---

extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetBuildingModelFilterField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/shared/layerContainers/3dtiles.tsx
extension/src/shared/layerContainers/hooks/useEvaluateBuildingModelFilter.ts
extension/src/shared/plateau/constants.ts
extension/src/shared/reearth/types/index.ts
extension/src/shared/types/fieldComponents/3dtiles.ts
extension/src/shared/view/fields/3dtiles/LayerTilesetBuildingModelFilterField.tsx
extension/src/shared/view/fields/Fields.tsx
extension/src/shared/view/fields/fieldSettings.ts

- You can use default building model to test it.

feat(extension): add building model filter

---

extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointUse3DModelField.tsx
extension/src/shared/layerContainers/general.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/reearth/hooks/index.ts
extension/src/shared/reearth/hooks/useLayer.ts
extension/src/shared/reearth/layers/3dtiles.ts
extension/src/shared/reearth/layers/general.ts
extension/src/shared/reearth/layers/gtfs.ts
extension/src/shared/reearth/layers/index.ts
extension/src/shared/types/fieldComponents/point.ts
extension/src/shared/view-layers/rootLayer.ts
extension/src/shared/view/fields/fieldSettings.ts

- Support GTFS
- Add PointUse3DModelField
|Marker|Model when zooming|
|:--:|:--:|
|![Screenshot 2023-11-15 at 12 45 21](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/3294886d-9a8a-4b9d-b9ba-49626753cf04)|![Screenshot 2023-11-15 at 12 45 37](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/e9e4f358-bcc1-4b75-b700-017a4edaee76)|
1. Search `バスロケーション`
2. You can see the marker.
3. When you zoom to the marker, then 3D model should appear

feat(extension): support gtfs

---

extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetFillColorGradientField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorFillColorConditionField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorFillColorGradientField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorFillColorValueField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorVisibilityFilterField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointImageSizeField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointSizeField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointUse3DModelField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/polygon/EditorPolygonStrokeWeightField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/polyline/EditorPolygonStrokeWeightField.tsx
extension/src/editor/containers/common/fieldComponentEditor/hooksUtils/index.ts
extension/src/editor/containers/common/fieldComponentEditor/hooksUtils/useNumberFieldState.ts
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/index.ts
extension/src/shared/types/fieldComponents/polyline.ts
extension/src/shared/view/fields/Fields.tsx
extension/src/shared/view/fields/common/LayerVisibilityFilterField.tsx
extension/src/shared/view/fields/fieldSettings.ts
extension/src/shared/view/fields/point/LayerPointVisibilityFilterField.tsx
extension/src/shared/view/fields/polyline/LayerPolylineFillColorConditionField.tsx
extension/src/shared/view/fields/polyline/LayerPolylineVisibilityFilterField.tsx

You can use `緊急輸送道路情報（東京都23区）` for testing.

feat(extension): color and visibility filter support for polyline

---

extension/src/prototypes/view/constants/datasetTypeNames.ts
extension/src/prototypes/view/constants/datasetTypeOrder.ts

I fixed the order of the search list UI. Also I fixed the search list to show usecase(ユースケース) data.

fix(extension): Search list order

---

extension/src/shared/layerContainers/general.tsx
extension/src/shared/reearth/layers/wms.ts

- You can use `NASA推定降水量データ（Global, IMERG_30Min）` to test this PR.

feat(extension): support wms

---

extension/src/editor/containers/common/fieldComponentEditor/fields/general/EditorLinkButtonField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/shared/types/fieldComponents/general.ts
extension/src/shared/view/fields/Fields.tsx
extension/src/shared/view/fields/fieldSettings.ts
extension/src/shared/view/fields/general/LayerLinkButtonField.tsx

You can use `建築物モデル（中央区）` to test this PR.

feat(extension): link button field

---

extension/src/prototypes/view/selection/TileFeatureContent.tsx
extension/src/shared/layerContainers/buildingModel.tsx
extension/src/shared/layerContainers/floodModel.tsx
extension/src/shared/layerContainers/hooks/useEvaluateFilter.ts
extension/src/shared/plateau/layers/TilesetFeatureIndex.ts
extension/src/shared/view-layers/plateau-3dtiles/BuildingLayer.tsx

- This should work only in BuildingModel.
- This should work even if building filter is used.
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/9e6f5a1c-b3bc-4088-8785-fbb989a402a0

feat(extension): support the functionality to hide features

---

extension/src/inspector/Widget.tsx
extension/src/prototypes/ui-components/AppOverlayLayout.tsx
extension/src/prototypes/ui-components/DatasetTreeView.tsx
extension/src/prototypes/view/ui-containers/AppOverlay.tsx
extension/src/prototypes/view/ui-containers/DatasetAreaList.tsx
extension/src/prototypes/view/ui-containers/DatasetTypeList.tsx
extension/src/search/Widget.tsx
extension/src/shared/ui-components/Spacer.tsx

Search widget and Inspector widget was overflowed from WAS grid. It causes the problem which we can't place other widget well. So I fixed this issue.

fix(extension): Work well on WAS

---

extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointStrokeField.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/point.ts
extension/src/shared/view/fields/fieldSettings.ts

You can use this data: `公園情報（東京都23区）`

feat(extension): point stroke field

---

extension/src/toolbar/hooks/useAttachScreenSpaceSelection.tsx

1. Add `土地利用`
2. Select area
3. Show feature inspector whenever there is a feature.

fix(extension): MVT could not be selected sometimes

---

extension/src/prototypes/cesium/ScreenSpaceElement.tsx
extension/src/prototypes/cesium/index.ts
extension/src/prototypes/pedestrian/LevitationCircle.tsx
extension/src/prototypes/pedestrian/Pedestrian.tsx
extension/src/prototypes/pedestrian/PedestrianObject.tsx
extension/src/prototypes/pedestrian/PedestrianTool.tsx
extension/src/prototypes/pedestrian/StreetViewFrustum.tsx
extension/src/prototypes/pedestrian/getFieldOfView.ts
extension/src/prototypes/pedestrian/useSynchronizeStreetView.tsx
extension/src/prototypes/view/selection/PedestrianLayerContent.tsx
extension/src/shared/reearth/layers/pedestrian/ellipse.ts
extension/src/shared/reearth/layers/pedestrian/frustum.ts
extension/src/shared/reearth/layers/pedestrian/index.ts
extension/src/shared/reearth/types/appearance.ts
extension/src/shared/reearth/types/camera.ts
extension/src/shared/reearth/types/scene.ts
extension/src/shared/reearth/utils/camera.ts

NOTE: Need https://github.com/reearth/reearth/pull/862.
I finalized to implement pedestrian feature.
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/e46a6e26-bd04-4c67-bdca-41f279468c68
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/3a1ca2a4-3d28-4216-974b-66fb26e35c79
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/d0a28629-e85e-4bee-abbd-0af5ed234fa9
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/a99231bc-4e99-44df-b64b-1ec9fed4ecf0

feat(extension): finalize pedestrian

---

extension/src/prototypes/view/environments/MapEnvironment.tsx

fix(extension): show shadow in 3dtiles

---

extension/src/shared/view-layers/rootLayer.ts

Fix to use default template if the dataset name is same with template name.

fix(extension): use default template

---

extension/src/editor/Widget.tsx
extension/src/prototypes/pedestrian/LevitationCircle.tsx
extension/src/prototypes/ui-components/SearchAutocomplete.tsx
extension/src/prototypes/view/hooks/useSearchOptions.ts
extension/src/prototypes/view/ui-containers/DatasetDialog.tsx
extension/src/prototypes/view/ui-containers/DatasetListItem.tsx
extension/src/shared/constants/localStorage.ts
extension/src/shared/context/WidgetContext.tsx
extension/src/shared/layerContainers/floodModel.tsx
extension/src/shared/reearth/utils/index.ts
extension/src/shared/reearth/utils/scene.ts
extension/src/shared/utils/color.ts
extension/src/shared/utils/index.ts
extension/src/shared/view-layers/rootLayer.ts

- Color of flood model
- Prevent resetting the input value in search field
- Override default template if there is some setting value
- Show the year of dataset in editor

fix(extension): some bugs

---

extension/src/shared/reearth/layers/pedestrian/marker.ts

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=1568b4f4018b45c2a5f47196048baf1c&pm=s

chore: add hideindicator on maker appearance

---

extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetWireframeField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/prototypes/ui-components/AppOverlayLayout.tsx
extension/src/shared/layerContainers/buildingModel.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/3dtiles.ts
extension/src/shared/view/fields/3dtiles/LayerTilesetWireframeField.tsx
extension/src/shared/view/fields/Fields.tsx
extension/src/shared/view/fields/fieldSettings.ts

What I have done:
- Add wireframe field in dataset editor
- Add wireframe display toggle in view

feat(extension): wireframe for 3dtiles

---

extension/src/prototypes/view/ui-containers/CameraButtons.tsx
extension/src/prototypes/view/ui-containers/GeolocationButton.tsx

What I have done:
- Implement the current location component and functionalities

feat(extension): current location

---

extension/src/shared/plateau/layers/TilesetProperties.ts

Need [this PR](https://github.com/reearth/reearth/pull/882)

fix(extension): use rootProperties

---

extension/src/editor/containers/ui-components/property/PropertyOperationSelectField.tsx
extension/src/editor/containers/ui-components/property/PropertySelectField.tsx
extension/src/shared/helpers/expression.ts
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts

feat(extension): support startsWith operator

---

extension/src/prototypes/ui-components/EntityTitleButton.tsx
extension/src/prototypes/ui-components/LayerListItem.tsx
extension/src/prototypes/view-layers/ViewLayerListItem.tsx

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=0e761f9682004948b070a20b7f1d6ab0&pm=s

chore(web): FlyTo icon on layer item

---

extension/src/prototypes/ui-components/PropertyParameterItem.tsx

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=32adc47bc4eb411eb27b73693dd33003&pm=s
Values rounded down to two decimal places

chore: Round float number in feature inspector

---

extension/src/shared/reearth/scene/Scene.tsx

fix(extension): use constant object value

---

extension/src/shared/reearth/layers/general.ts
extension/src/shared/reearth/layers/mvt.ts
extension/src/shared/reearth/layers/wms.ts
extension/src/shared/reearth/types/appearance.ts

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=5a8dbc7df50f4aaf8b4bb7575e2b2f00&pm=s

chore: Hide indicator for all appearance

---

extension/src/shared/utils/number.test.ts
extension/src/shared/utils/number.ts

Rounded down to two decimal places
ALL Test Files have passed

chore: Rounded down to two decimal places

---

extension/src/prototypes/layers/LayerList.tsx

feat(extension): add remove all button on layers list

---

extension/src/prototypes/view/containers/Environments.tsx
extension/src/prototypes/view/states/app.ts
extension/src/prototypes/view/ui-containers/EnvironmentSelect.tsx
extension/src/shared/states/scene.ts

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=8308f2e16e264e76864ea372f90e8cf6&pm=s
shared url: http://localhost:3000/scene/01hnc92z2k2re4drj0710wqzpc/map?share=01hpettze3sx38z4yetp71p4fr

chore: Share for map label

---

extension/src/prototypes/ui-components/EntityTitleButton.tsx
extension/src/prototypes/ui-components/LayerListItem.tsx

move fly to icon on hover menu

chore: Layer fly to icon is Wrong

---

extension/src/prototypes/ui-components/LayerListItem.tsx

https://eukarya-inc.slack.com/archives/C0699MLE7PZ/p1707960066477699

chore: fix icon color for button

---

extension/src/shared/layerContainers/utils/value.ts
extension/src/shared/view/selection/ColorSchemeSectionForComponentField.tsx
extension/src/shared/view/selection/ImageSchemaSectionForComponentField.tsx
extension/src/shared/view/state/colorSchemeForComponent.ts
extension/src/shared/view/state/imageSchemaForComponent.ts

rules[0] could be undefined and could leads to crash.

fix(extension): rules[0] could be undefined

---

extension/src/shared/view/selection/GeneralFeatureContent.tsx

What I did
- Added feature inspector button to select parent layer.

feat(extension): added inspector button

---

extension/src/editor/containers/dataset/FeatureInspectorPage.tsx
extension/src/editor/containers/dataset/FieldComponentsPage.tsx

Add key to the component to trigger re-render properly.

fix(extension): editor dataset feature inspector emphasis property key

---

extension/src/shared/layerContainers/buildingModel.tsx
extension/src/shared/layerContainers/general.tsx
extension/src/shared/layerContainers/hooks/useClippingBox.ts
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/reearth/layers/3dtiles.ts
extension/src/shared/reearth/types/appearance.ts
extension/src/shared/reearth/types/value.ts

Avoid select clipping box in select mode

chore: Avoid select clipping box in select mode

---

extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorFillAndStrokeColorConditionField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorFillColorConditionField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorFillColorGradientField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorVisibilityFilterField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointUseImageConditionField.tsx
extension/src/shared/layerContainers/utils/value.ts
extension/src/shared/view/selection/ColorSchemeSectionForComponentField.tsx
extension/src/shared/view/selection/ImageSchemaSectionForComponentField.tsx
extension/src/shared/view/state/colorSchemeForComponent.ts
extension/src/shared/view/state/imageSchemaForComponent.ts

It is required to set default rule for condition fields.
If any rule set asDefaultRule to true, it will have higher priority than component useDefault setting.

feat(extention): support set default rule for condition fields

---

extension/src/prototypes/view/ui-containers/DatasetDialog.tsx

Previous fix PR removed sub title but actually need to remove subname.

fix(extension): remove subname instead of sub title in dataset dialog

---

extension/src/shared/view/containers/InitialLayers.tsx

Since we initialize will only be triggered once we should not have the return function which is removing exist initial layer.

fix(extension): remove return function of initial layer

---

extension/src/shared/plateau/colorSets/buildingColor.ts

https://eukarya.notion.site/04d52aca29284ff0aee315f09a6357e6#46106f9754564dba9dd941a2c07b0e19

chore: Change color for 用途 for building model

---

extension/src/prototypes/view/ui-containers/DatasetAreaList.tsx
extension/src/prototypes/view/ui-containers/DatasetTypeList.tsx

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=c6eabbc26ec1451b953cd897c15607a1&pm=s

chore: Show title for usecase

---

extension/src/prototypes/view/ui-containers/DatasetTypeList.tsx

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=c3176fd18da24e7bb52dc727fdcce67a&pm=s

chore: Title for usecase

---

extension/src/prototypes/view/ui-containers/DatasetDialog.tsx

Title should not be shrinkable.

fix(extension): dataset dialog title height

---

extension/src/prototypes/view/hooks/useSearchOptions.ts

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=1a96cf3a3c6a45559daa11c8340221ee&pm=s

chore: Show city in search

---

extension/src/prototypes/ui-components/LightThemeOverride.tsx
extension/src/shared/ui-components/Modal.tsx
extension/src/shared/ui-components/ShareModal/index.tsx

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=673a995b6d6f4680858d571cf5267a61&pm=s

chore: Share Modal should be white theme ( same as other modal )

---

extension/src/prototypes/view/containers/KeyBindings.tsx
extension/src/prototypes/view/containers/KeyboardHandlers.ts
extension/src/toolbar/Widget.tsx

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=fe7111d0cc3843a587ab9f61cb61af0e&pm=s

chore: keyboard shortcut for interaction mode

---

extension/src/prototypes/view/ui-containers/FileDrop.tsx
extension/src/toolbar/Widget.tsx

This PR adds the support for import sketch layer by drop file

feat(extension): support import sketch layer by drop file

---

extension/src/prototypes/view/environments/MapEnvironment.tsx

Need this PR: https://github.com/reearth/reearth/pull/914

fix(extension): tile zoom level

---

extension/src/shared/reearth/layers/general.ts
extension/src/shared/reearth/types/appearance.ts

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=1b658da20c0c4c7394fbdeb572c99c8a&pm=s

chore: Hide indicator for resource

---

extension/src/prototypes/view/ui-containers/DefaultDatasetSelect.tsx

https://www.notion.so/eukarya/Development-Management-151ba655e06c4b499b0a8935b238c6dd?p=35025260727f433983461b8b5574621c&pm=s

chore: 洪水浸水想定区域モデルにおいてデータセット1つしかない場合「計画規模」「想定最大規模」のどちらかなのか分からない

---

terraform/gcp/README.md
terraform/gcp/modules/reearth/google_cloud_run_v2_service.tf
terraform/gcp/modules/reearth/google_storage_bucket.tf
terraform/gcp/modules/reearth_cms/google_project_iam_custom_role.tf
terraform/gcp/modules/reearth_cms/google_service_account_iam_member.tf
terraform/gcp/modules/reearth_cms/google_storage_bucket.tf
terraform/gcp/modules/reearth_cms/output.tf
terraform/gcp/terraform.tfvars.example

Because some of the new feature's permissions were missing 🙏 
Also, I have added the default values for the `tfvar`.

fix(terraform): add missing permission for CMS and update CORS for asset buckets

---

extension/src/prototypes/view-layers/createViewLayerModel.ts
extension/src/shared/layerContainers/utils/color.ts
extension/src/shared/states/share.ts
extension/src/shared/view-layers/rootLayer.ts
extension/src/shared/view/containers/InitialLayers.tsx

This PR supports sharing with layer hidden state, including dataset layer and all other layer types.
This PR also did a small refactor on `colorWithAlpha` to support short hex color string.

feat(extension): support share hidden state

---

extension/src/prototypes/view-layers/HeatmapLayer.tsx
extension/src/shared/states/share.ts
extension/src/shared/view/containers/InitialLayers.tsx

The shared layers should keep the original order when initialize.

fix(extension): initial layers order

---

extension/src/prototypes/view/ui-containers/CompassButton.tsx

This PR updates the compass button behavior as reset heading only.

refactor(extension): reset heading when click compass button

---

extension/src/prototypes/view/ui-containers/DatasetAreaList.tsx

fix(extension): some dataset type missing in area list

---

extension/src/prototypes/ui-components/AppOverlayLayout.tsx

https://www.notion.so/eukarya/Inspector-max-height-keep-50-window-height-f82f5eb2253945c4872ae7cf266f5cbf

Inspector max height keep 50% window height

---

extension/src/prototypes/screen-space-selection/ScreenSpaceSelection.tsx
extension/src/prototypes/screen-space-selection/ScreenSpaceSelectionEvent.ts
extension/src/prototypes/screen-space-selection/ScreenSpaceSelectionHandler.ts
extension/src/prototypes/view/containers/ScreenSpaceSelection.tsx

Line feature wasn't selectable. So I fixed to use the select event other than the building model.
- Search `緊急輸送道路情報` and `鉄道情報`.
- Select feature, then it should show the feature inspector.

fix(extension): select line feature

---

extension/src/prototypes/ui-components/Inspector.tsx
extension/src/prototypes/view/ui-containers/DatasetDialog.tsx

i needed to fix layer and feature inspectors too
https://www.notion.so/eukarya/Inspector-max-height-keep-50-window-height-f82f5eb2253945c4872ae7cf266f5cbf

chore: max height for layer inspectors

---

extension/src/shared/view/containers/InitialLayers.tsx

Revert[ the fix](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/commit/a750bc07792e0f7353b7f596167e3d4c93aedb6e) since it has been pushed to main branch directly by mistake.
I'll make a PR for the fix for better management.

fix(extension): revert previous fix for initial layer

---

extension/src/shared/view/containers/InitialLayers.tsx

The initial datasets from settings were not been added.

fix(extension): initial dataset layer can't be load

---

extension/src/prototypes/view/ui-containers/MainMenuButton.tsx
extension/src/shared/constants/api.ts
extension/src/shared/context/WidgetContext.tsx
extension/src/toolbar/Widget.tsx

fix(extension): feedback not hiding

---

.github/workflows/deploy-cms-dev.yml

* Modify deploy_server_worker condition
* Test on push trigger temoporary ([result](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/actions/runs/8761724907))

ci: refactor condition

---

.github/workflows/deploy-cms-prod.yml

Fix skip condition for deploy to prod cms
* test: https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/actions/runs/8762241961

ci: fix condition for prod deployment

---

extension/src/shared/view/containers/JapanPlateauPolygon.tsx

Reverts eukarya-inc/PLATEAU-VIEW-3.0#310

Revert "fix(extension): use show property to toggle Japan polygon"

---

extension/src/shared/view/containers/JapanPlateauPolygon.tsx

There was a performance issue.
Re: https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/pull/310

fix(extension): use show property to toggle Japan polygon

---

extension/src/shared/ui-components/MyData/LocalDataTab.tsx
extension/src/shared/ui-components/MyData/WebDataTab.tsx

The type was only been considered during the process of handle uploaded file, if you change type after the upload process it will take no effect. This PR fixes this bug on local data tab and also web data tab.

fix(extension): type selection take no effect after file been uploaded on MyData modal

---

extension/src/shared/layerContainers/myData.tsx
extension/src/shared/ui-components/MyData/LocalDataTab.tsx
extension/src/shared/ui-components/MyData/utils.ts
extension/src/shared/view/ui-container/MyData.tsx

This PR fixes my data's local data not working format which are not text based i.e zip etc. Instead of reading local data as text we now read it as URL.

fix(extension): read local data as data URL in my data

---

extension/src/shared/ui-components/TimelineBarForPastTime.tsx
extension/src/shared/ui-components/TimelineParameterItem.tsx

Display past time instead of time point value on slider when time display type is past time.

refactor(extension): display past time on timeline slider when time display type is past time

---

extension/src/prototypes/view/ui-containers/DatasetGroup.tsx
extension/src/prototypes/view/utils/datasetGroups.test.ts
extension/src/prototypes/view/utils/datasetGroups.ts

City data without `/` in name needs to be displayed directly.

fix(extension): display city data without folder

---

.github/workflows/build-geo.yml
.github/workflows/build-server.yml
.github/workflows/build-worker.yml
.github/workflows/ci-tools.yml
.github/workflows/deploy-cms-dev.yml
.github/workflows/deploy-reearth-dev.yml
.github/workflows/deploy-reearth-visualizer-dev.yml

Upgrade `actions/upload-artifact` and `actions/download-artifact` to v4

chore: upgrade action upload artifact

---

server/datacatalog/repos.go

Fixed the handling of cases where municipalities without citygml were included

fix(server): Fixed the handling of cases where municipalities without citygml were included

---

extension/src/editor/containers/common/commonTemplate/TemplateHeader.tsx
extension/src/editor/containers/component-template/index.tsx
extension/src/editor/containers/emphasis-property-template/index.tsx
extension/src/prototypes/ui-components/ContextSelect.tsx
extension/src/prototypes/view/ui-containers/DatasetTreeSelect.tsx
extension/src/prototypes/view/ui-containers/DefaultDatasetSelect.tsx
extension/src/prototypes/view/ui-containers/LocationBreadcrumbItem.tsx
extension/src/prototypes/view/utils/datasetGroups.test.ts
extension/src/prototypes/view/utils/datasetGroups.ts
extension/src/shared/constants/dataset.ts
extension/src/shared/constants/index.ts
extension/src/shared/graphql/hooks/catalog/area.ts

Reverts eukarya-inc/PLATEAU-VIEW-3.0#363

Revert "Revert "chore: revert some features""

---

extension/src/shared/helpers/expression.ts
extension/src/shared/ui-components/MyData/LocalDataTab.tsx
extension/src/shared/ui-components/MyData/WebDataTab.tsx

Merge latest `main` branch into `dev`

chore(extension): merge main to dev

---

.github/workflows/deploy-reearth-visualizer-prod.yml

Because we want to migrate to Cloud Run from GCS just like we did in development.

ci: add Visualizer Web deploy for prod

---

.github/workflows/deploy-reearth-classic-dev.yml
.github/workflows/deploy-reearth-classic-prod.yml

To deploy the Cloud Run-ed Classic web.

ci: add Re:Earth Classic web deploy job

---

.github/workflows/deploy-reearth-classic-dev.yml
.github/workflows/deploy-reearth-classic-prod.yml

ci: classic-web image to deploy

---

.github/workflows/deploy-reearth-classic-prod.yml

ci: remove no need push in Classic Web

---

.github/workflows/deploy-reearth-visualizer-dev.yml

We only release release candidates!

ci: use `rc` tag for Visualizer

---

extension/src/shared/reearth/scene/Scene.tsx

refactor(extension): update geoid height api

---

extension/src/prototypes/ui-components/PropertyParameterItem.tsx
extension/src/prototypes/view/selection/LayerMeshCodeSection.tsx
extension/src/prototypes/view/selection/MeshCodeObjectContent.tsx

- Remove city properties.
- Add a description above packs.

refactor(extension): update ui on selection panel of mesh code layer
