eukarya-inc/PLATEAU-VIEW

extension/reearth-yml.ts
extension/src/prototypes/ui-components/AppBar.tsx
extension/src/prototypes/ui-components/AppOverlayLayout.tsx
extension/src/prototypes/ui-components/SearchField.tsx
extension/src/prototypes/view/containers/Environments.tsx
extension/src/prototypes/view/environments/ElevationEnvironment.tsx
extension/src/prototypes/view/environments/GooglePhotorealisticEnvironment.tsx
extension/src/prototypes/view/environments/MapEnvironment.tsx
extension/src/prototypes/view/environments/SatelliteEnvironment.tsx
extension/src/prototypes/view/ui-containers/EnvironmentSelect.tsx
extension/src/prototypes/view/ui-containers/SettingsPanel.tsx
extension/src/shared/reearth/hooks/useView.ts
extension/src/shared/reearth/layers/3dtiles.ts
extension/src/shared/reearth/scene/Scene.tsx
extension/src/shared/reearth/scene/index.ts
extension/src/shared/reearth/types/camera.ts
extension/src/shared/reearth/types/scene.ts
extension/src/shared/sharedAtoms/atom.ts
extension/src/shared/sharedAtoms/store.ts
extension/src/shared/states/scene.ts
extension/src/toolbar/Widget.tsx

NOTE: To work this PR, this PR is necessary. https://github.com/reearth/reearth/pull/663
I added a basic scene support.
- Same view with VIEW3.0 prototype
- The `map` type base-map is an alternative. I will update this after the same one with prototype is implemented.
- Share scene feature
- You can test the share feature by adding `?share=123`.

feat(extension): Basic scene support

---

extension/src/prototypes/view/containers/ReverseGeocoding.tsx
extension/src/prototypes/view/hooks/useReverseGeocoder.ts
extension/src/prototypes/view/ui-containers/LocationBreadcrumbs.tsx
extension/src/shared/graphql/base/__gen__/gql.ts
extension/src/shared/graphql/base/__gen__/graphql.ts
extension/src/shared/graphql/base/queries/areas.ts
extension/src/shared/graphql/hooks/areas.ts
extension/src/shared/graphql/hooks/base.ts
extension/src/shared/graphql/hooks/index.ts
extension/src/shared/reearth/types/camera.ts
extension/src/shared/states/address.ts
extension/src/toolbar/Widget.tsx

This PR connect location bread crumbs with reearth camera move & areas API.
Currently using AppBreadcrumbsItem to display the area names, didn't implement the popup with layers etc.
m

feat(extension): connect location bread crumbs

---

extension/src/sampleEditor/Widget.tsx
extension/src/shared/layerContainers/3dtiles.tsx
extension/src/shared/layerContainers/general.tsx
extension/src/shared/view-layers/3dtiles/BuildingLayer.tsx
extension/src/shared/view-layers/component.ts
extension/src/shared/view/fields/general/LayerOpacityField.tsx

I fixed the component atom to take the entire field component which is set from editor. Therefore we can refer the setting value from editor in viewer.

fix(extension): component atom for viewer

---

extension/src/prototypes/ui-components/editor/EditorPanel.tsx
extension/src/prototypes/view/ui-containers/editorContainers/common/fieldComponentEditor/fields/point/EditorPointColorField.tsx
extension/src/prototypes/view/ui-containers/editorContainers/common/fieldComponentEditor/fields/point/EditorPointSizeField.tsx
extension/src/prototypes/view/ui-containers/editorContainers/dataset/index.tsx
extension/src/sampleEditor/Widget.tsx
extension/src/shared/api/constants.ts
extension/src/shared/api/hooks/settings.ts
extension/src/shared/api/mock.ts
extension/src/shared/api/types/component.ts
extension/src/shared/layerContainers/general.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/reearth/layers/general.ts
extension/src/shared/states/setting.ts
extension/src/shared/view-layers/general/GeneralDatasetLayer.tsx
extension/src/shared/view-layers/rootLayer.ts
extension/src/shared/view/fields/fieldSettings.ts

I setup the connection with the common state between viewer and editor. But I haven't done API connection yet. I will work on it after this PR.
You can test as follows.
1. Select dataset(e.g. ランドマーク)
2. Default appearance is displayed first
3. You can add `Point color` and `Point size` field which have hard coded value.
4. Click apply button, then the setting is attached.

feat(extension): connect the common state between editor and viewer

---

extension/src/editor/containers/common/commonTemplate/TemplateAddButton.tsx
extension/src/editor/containers/component-template/index.tsx
extension/src/editor/containers/dataset/blocks/StatusBlock.tsx
extension/src/editor/containers/dataset/index.tsx
extension/src/editor/containers/emphasis-property-template/index.tsx
extension/src/editor/containers/index.tsx
extension/src/editor/containers/ui-components/editor/EditorNotice.tsx
extension/src/editor/containers/ui-components/editor/EditorPanel.tsx

This PR 
- adds a EditorNotice and use after saving on editor.
- adds status control for save button when saving.
- update style for StatusBlock a little bit.

feat(extension): add notice and status control for editor saving

---

extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetFillColorConditionField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetFillColorGradientField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/prototypes/view/hooks/useSearchOptions.ts
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/reearth/layers/general.ts
extension/src/shared/types/fieldComponents/3dtiles.ts
extension/src/shared/view-layers/componentField.ts
extension/src/shared/view/fields/3dtiles/LayerTilesetFillColorConditionField.tsx
extension/src/shared/view/fields/3dtiles/LayerTilesetFillGradientColorField.tsx
extension/src/shared/view/fields/Fields.tsx
extension/src/shared/view/fields/fieldSettings.ts

- Added `TilesetFillColorConditionField` and `TilesetFillColorGradientField`.
- Fix some bugs around usecase data.
You can use `建築物モデル動作確認` data for testing.

feat(extension): Add 3dtiles color fields

---

extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetClippingField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/shared/layerContainers/3dtiles.tsx
extension/src/shared/layerContainers/hooks/useClippingBox.ts
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/reearth/layers/3dtiles.ts
extension/src/shared/reearth/types/reearth.ts
extension/src/shared/reearth/types/viewport.ts
extension/src/shared/types/fieldComponents/3dtiles.ts
extension/src/shared/view-layers/3dtiles/BuildingLayer.tsx
extension/src/shared/view-layers/hooks.ts
extension/src/shared/view/fields/3dtiles/LayerTilesetClippingField.tsx
extension/src/shared/view/fields/Fields.tsx
extension/src/shared/view/fields/fieldSettings.ts

- Add clipping box field
- Some refactor
- Test use case data with `建築物モデル動作確認（大阪市都島区）`
- Test plateau building model

feat(extension): add clipping box field

---

extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorVisibilityFilterField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/point.ts
extension/src/shared/types/fieldComponents/polygon.ts
extension/src/shared/view/fields/Fields.tsx
extension/src/shared/view/fields/common/LayerPolygonVisibilityFilterField.tsx
extension/src/shared/view/fields/fieldSettings.ts
extension/src/shared/view/fields/polygon/LayerPolygonVisibilityFilterField.tsx

- You can use `土地利用モデル（東京都23区）` with `visibility` group for testing

feat(extension): visibility filter field for polygon

---

extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/colorScheme.ts
extension/src/shared/view/fields/fieldSettings.ts
extension/src/shared/view/fields/polygon/LayerPolygonFillColorConditionField.tsx
extension/src/shared/view/selection/ColorSchemeSectionForComponentField.tsx
extension/src/shared/view/selection/ImageSchemaSectionForComponentField.tsx
extension/src/shared/view/state/colorSchemeForComponent.ts
extension/src/shared/view/state/imageSchemaForComponent.ts

I fixed to use first rule as default in some field which has condition. Basically general layer other than BuildingModel and FloodModel should use first rule as default.
For VisibilityFilter, I fixed it in [another PR](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/pulls).

fix(extension): use first rule as default

---

extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetFillColorGradientField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorFillColorGradientField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointImageSizeField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointSizeField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointUse3DModelField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/polygon/EditorPolygonStrokeWeightField.tsx
extension/src/editor/containers/common/fieldComponentEditor/hooksUtils/index.ts
extension/src/editor/containers/common/fieldComponentEditor/hooksUtils/useNumberFieldState.ts

I fixed some number field to be empty value. For example, it's just `0` when you remove all text from a number field. And we can't change value. I fixed this issue.
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/f4902b8a-d817-4abd-9f7a-b5f89cd4827f

fix(extension): better number field

---

extension/src/shared/view/state/colorSchemeForComponent.ts
extension/src/shared/view/state/imageSchemaForComponent.ts

I fixed to use `asLegend` to display a legend. Legend should be shown when `asLegend` is enabled.
|asLegend|none|
|:--:|:--:|
|![Screenshot 2023-11-17 at 16 14 21](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/b5d838b0-10b5-4355-b937-39d5f858f686)|![Screenshot 2023-11-17 at 16 14 29](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/e8e00ed6-a091-43ec-b80d-9792f6456273)|

fix(extension): use asLegend to filter using legend

---

extension/src/shared/types/fieldComponents/imageScheme.ts
extension/src/shared/types/fieldComponents/point.ts
extension/src/shared/view-layers/componentField.ts
extension/src/shared/view/fields/fieldSettings.ts
extension/src/shared/view/state/colorSchemeForComponent.ts
extension/src/shared/view/state/imageSchemaForComponent.ts

I fixed legend inspector to display simple value field like FillColorValueField, UseImageValueField.
|color|image|
|:--:|:--:|
|![Screenshot 2023-11-17 at 18 00 07](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/5f35a418-e6a2-4b97-aa75-c94bcaa6b1ae)|![Screenshot 2023-11-17 at 18 03 25](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/807a8dc7-5d5e-4c39-b116-8ea10d7cdb68)|

fix(extension): support legend for simple value field

---

extension/src/editor/containers/ui-components/editor/EditorNotice.tsx
extension/src/prototypes/ui-components/OverlayPopper.tsx
extension/src/shared/reearth/constants/style.ts

I fixed z-index for popover because the z-index of WAS is changed in [this commit](https://github.com/reearth/reearth/pull/751/files#diff-41a2cd990413b37710725ee60028ed47233f13c47d14a107ee33862574465621R3).

fix(extension): z-index for WAS

---

extension/src/shared/reearth/hooks/useLayer.ts

I fixed layer to initialize without appearance. In NLS, initial appearance should be used as default value when you override the appearance with `undefined`.

fix(extension): fix layer to initialize without appearance to be resettable

---

extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorClassificationTypeField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorHeightReferenceField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/point.ts
extension/src/shared/types/fieldComponents/polygon.ts
extension/src/shared/types/fieldComponents/polyline.ts
extension/src/shared/view/fields/fieldSettings.ts

You can use `緊急輸送道路情報（東京都23区）` to test this PR.
The different part of the following images is the part of the drawn circle.
|Classification: both|Classification: terrain|
|:--:|:--:|
|![Screenshot 2023-11-24 at 10 41 30](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/7407dbf3-cb16-4df9-8744-62b48f06ecd5)|![Screenshot 2023-11-24 at 10 40 32](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/7b114055-113a-4bfd-b5ae-c35053b585d8)|

feat(extension): add height reference and classification type field

---

extension/src/prototypes/view/hooks/useSearchOptions.ts
extension/src/prototypes/view/selection/LayerContent.tsx
extension/src/prototypes/view/ui-containers/BuildingDatasetButtonSelect.tsx
extension/src/prototypes/view/ui-containers/DatasetDialog.tsx
extension/src/prototypes/view/ui-containers/DatasetListItem.tsx
extension/src/prototypes/view/ui-containers/DefaultDatasetButton.tsx
extension/src/prototypes/view/ui-containers/DefaultDatasetSelect.tsx
extension/src/shared/view-layers/rootLayer.ts
extension/src/shared/view/containers/InitialLayers.tsx

I fixed to display the dataset reference on layer inspector.
It will be displayed only when single layer is selected. (If multiple layers are selected, the icon button will be disabled.)

fix(extension): display the dataset reference on layer inspector

---

extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointUseLabelField.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/point.ts
extension/src/shared/view/fields/fieldSettings.ts

This PR adds point use label field.
Need [this](https://github.com/reearth/reearth/pull/834) to display the extrude line.
You can still use `避難施設情報（中央区）` to test

feat(extension): point use label field

---

extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/editor/containers/ui-components/component/ComponentSelector.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts

This PR changes the behavior of style code field.
[BEFORE]
- Style code should be conflict with all other appearance field components. (aka user can only choose use style code component OR use other components)
[AFTER]
- Style code is NOT conflict with any other field component.
- Style code will act as a basic appearce object if set. If user adds any other field component, their appearance will be merged and override the style from style code component.
You can still use `避難施設情報（中央区）` to test

refactor(extension): style code contribute appearance

---

extension/src/prototypes/ui-components/DateControl.tsx
extension/src/prototypes/view/ui-containers/DateControlButton.tsx
extension/src/prototypes/view/ui-containers/DateControlPanel.tsx
extension/src/shared/reearth/hooks/useCamera.ts
extension/src/shared/reearth/hooks/useTimeline.ts
extension/src/toolbar/containers/InitializeApp.tsx

This PR adds daytime panel.
Also set default time to 10 a.m. JST of current date when initialize app.
Features:
- Should always follow reearth time.
- Should keep updating while dataset timeline playing.
- Should interrupt dataset timeline play if do any act on daytime panel.
- Should always display time with JST.
- Year is selectable on UI.
You can play with dataset `東日本大震災時の帰宅困難者（東京駅周辺）` to test.

feat(extension): daytime panel

---

extension/src/prototypes/ui-components/InspectorActions.tsx
extension/src/prototypes/ui-components/InspectorHeader.tsx
extension/src/prototypes/view-layers/states.ts
extension/src/prototypes/view/selection/LayerContent.tsx
extension/src/shared/hooks/useOptionalAtom.ts
extension/src/shared/layerContainers/buildingModel.tsx
extension/src/shared/ui-components/MultipleSelectSearch.story.tsx
extension/src/shared/ui-components/MultipleSelectSearch.tsx
extension/src/shared/view-layers/plateau-3dtiles/BuildingLayer.tsx
extension/src/shared/view-layers/plateau-3dtiles/createPlateauTilesetLayerState.ts
extension/src/shared/view/containers/BuildingSearchPanel.tsx
extension/src/toolbar/hooks/useAttachScreenSpaceSelection.tsx

The behavior should be same with VIEW2.0, but there are some different behavior.
- The state of search will be kept until the layer inspector is deleted.
- Due to the above of reason, we can not select feature while searching, because the feature inspector will replace the layer inspector.
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/34934510/d74782e6-6718-4ce9-9667-9b0a1f891585

feat(extension): add building search panel

---

extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointUseLabelField.tsx
extension/src/shared/api/hooks/settings.ts
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts

This PR fixes the expression of point label text. 
- Now it matches the logic of View 2.0.
When use expression user should input start with `=`, like `=${名称}`. otherwise input will be treated as a simple text.
- Fix the unit of height in UI. It should be `meter` not `px`.
- Fix settings save logic. Check for exist setting item before save. 
Test with `リアルタイムデータ/西武バス バス関連リアルタイム`

fix(extension): point use label expression

---

extension/src/editor/containers/common/fieldComponentEditor/fields/general/EditorDatasetStoryField.tsx
extension/src/editor/containers/ui-components/property/PropertyCameraInput.tsx
extension/src/shared/view/fields/general/LayerDatasetStoryField.tsx

This PR fixes the issue that when switch pages on editor dataset story field, the content is not updated if target page's content is undefined.
Create multple pages and type in some text to one of them. Then switch pages.

fix(extension): dataset story field page content not updated correctly

---

extension/src/shared/view-layers/rootLayer.ts
extension/src/shared/view/selection/GeneralFeatureContent.tsx

- Fixed the issue that property list is not displayed when display type is `auto` in feature inspector setting.
- Fixed to use emphasis property which is set directly from feature inspector section in dataset editor.
- To display feature inspector for MVT when display type is `auto`.
- To display emphasis property which is set from dataset editor.

fix(extension): auto feature inspector type & support emphasis property from dataset editor

---

extension/src/prototypes/layers/states.ts
extension/src/prototypes/view-layers/states.ts
extension/src/prototypes/view/hooks/useSearchOptions.ts
extension/src/prototypes/view/selection/LayerContent.tsx
extension/src/prototypes/view/selection/TileFeatureContent.tsx
extension/src/prototypes/view/selection/TileFeaturePropertiesSection.tsx
extension/src/prototypes/view/states/selection.ts
extension/src/prototypes/view/ui-containers/BuildingDatasetButtonSelect.tsx
extension/src/prototypes/view/ui-containers/DatasetDialog.tsx
extension/src/prototypes/view/ui-containers/DatasetListItem.tsx
extension/src/prototypes/view/ui-containers/DefaultDatasetButton.tsx
extension/src/prototypes/view/ui-containers/DefaultDatasetSelect.tsx
extension/src/shared/plateau/featureInspector/utils.ts
extension/src/shared/states/rootLayer.ts
extension/src/shared/view-layers/createViewLayer.ts
extension/src/shared/view-layers/plateau-3dtiles/BuildingLayer.tsx
extension/src/shared/view-layers/rootLayer.ts
extension/src/shared/view/containers/InitialLayers.tsx
extension/src/shared/view/selection/GeneralFeatureContent.tsx
extension/src/shared/view/selection/GeneralFeaturePropertiesSection.tsx
extension/src/shared/view/selection/SwitchDatasetSection.tsx
extension/src/shared/view/selection/SwitchGroupSection.tsx

I did refactor to separate root layer type. Because current RootLayer supports only layer which depends on dataset. So I fixed to be able to have just a layer.
- The `dataset` type of root layer is used for layer which come from dataset.
- This type of layer has some information like component field.
- The `layer` type of root layer is used for custom layer like pedestrian layer, storyteling layer, etc.
- This type of layer has only layer related information basically.
By using [createRootLayerForLayerAtom](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/blob/b511a803fd2faeb909f4473ad9de4e57a218b18d/extension/src/shared/view-layers/rootLayer.ts#L379), we can add pedestrian layer, sketch layer, and storytelling layer.

refactor(extension): separate layer for dataset and custom layer like pedestrian layer, storytelling layer

---

extension/src/shared/plateau/featureInspector/utils.test.ts
extension/src/shared/plateau/featureInspector/utils.ts

- The visibility of property should be change through feature inspector editor
- Support process field
- Expression should look like `[value || value2, result]`

fix(extension): support process field and visible

---

extension/src/editor/containers/dataset/index.tsx
extension/src/prototypes/view-layers/ViewLayerListItem.tsx
extension/src/prototypes/view-layers/states.ts

I improved to use `highlightedLayer` in `LayerList` and `Editor`.
- In `LayerList`, the item should be highlighted when feature is selected.
- In `Editor`, the dataset editor should open when feature is selected.

fix(extension): use highlightedLayer

---

extension/src/prototypes/view/hooks/useSearchOptions.ts
extension/src/prototypes/view/ui-containers/SearchAutocompletePanel.tsx

I fixed two issue around search panel.
- Fix to be able to search in some keywords like `東京 建物`
- Fix to show the dataset around camera position.(It means the dataset should be changed by camera position)

fix(extension): search logic

---

extension/src/prototypes/view/ui-containers/LocationBreadcrumbItem.tsx

You can check if the breadcrumb shows the datasets in this city.
```
reearth.camera.flyTo({"lng":138.15293058963817,"lat":35.98832778314308,"height":3866.763694033752,"heading":0.9404687882328835,"pitch":-1.4582140824113208,"roll":0.00010674425193712977,"fov":1.0471975511965976,"aspectRatio":1.5610079575596818});
```

fix(extension): the issue which some dataset is not shown in some city

---

extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetFloodColorField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/prototypes/datasets/atomsWithQualitativeColorSet.ts
extension/src/prototypes/datasets/colorSets/floodRankColorSet.ts
extension/src/shared/layerContainers/floodModel.tsx
extension/src/shared/plateau/layers/TilesetProperties.ts
extension/src/shared/types/fieldComponents/3dtiles.ts
extension/src/shared/types/fieldComponents/colorScheme.ts
extension/src/shared/view/fields/Fields.tsx
extension/src/shared/view/fields/fieldSettings.ts
extension/src/shared/view/hooks/useIsMultipleSelectableField.ts

I added FloodColor field to customize the rank, the legend and the color. We need to customize these thing(rank, legend and color), but we need to decide the attribute in runtime due to there is a case to need to check tileset.json. So we can't customize the expression by this field.
You can use `Test-kya/flood-color` template in the flood model like `洪水浸水想定区域モデル`.

feat(extension): flood color field

---

extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorFillAndStrokeColorConditionField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/common/EditorFillColorConditionField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/point/EditorPointUseImageConditionField.tsx
extension/src/editor/containers/ui-components/property/PropertyConditionField.tsx
extension/src/editor/containers/ui-components/property/PropertyOperationSelectField.tsx
extension/src/editor/containers/ui-components/property/PropertyWrapper.tsx
extension/src/shared/layerContainers/utils/value.ts
extension/src/shared/view/selection/ColorSchemeSectionForComponentField.tsx
extension/src/shared/view/selection/ImageSchemaSectionForComponentField.tsx

There's a requirement to set the propertyName for each condition.
Before: we are assuming all conditions in one rule will base on one single property (set in rule's `propertyName`).
After: conditions could set its own `propertyName`. If not set it will still use rule's `propertyName`.

refactor(extension): support condition property name

---

extension/src/prototypes/view/ui-containers/DatasetDialog.tsx

In this PR:
- Update the title of dataset info panel.
- Primary title: `dataset.type.name` -> `dataset.name`
- Secondary title: `dataset.city.name` -> `dataset.prefecture.name`
- Update the title style, enlarge font size and bold the primary title.
- Set max width of the panel to device max width.
| Before | After |
| -- | -- |
| ![reearth plateau dev reearth io_dashboard_01habs59h8wcdbj60mqe0syrek(Desktop 1920)](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/21994748/a0b393a8-143c-4ee2-9e39-b06e3b41fde0) | ![localhost_3000_scene_01hnyhekfpzjhh81qhg61vveg5_widgets(Desktop 1920) (16)](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/21994748/b28609b2-318d-4845-9efd-2aec14e0e148) |

fix(extention): dataset info title and style

---

extension/src/inspector/Widget.tsx
extension/src/prototypes/view/ui-containers/SearchAutocompletePanel.tsx
extension/src/search/Widget.tsx
extension/src/shared/ui-components/common/ViewClickAwayListener.tsx
extension/src/toolbar/Widget.tsx

Click event on each reearth widget seem been stopped from propagation to body (not sure where did that though). Therefore the ClickAwayListener of mui can't work well.
This PR adds a common ViewClickAwayListener component and hardcoded the DOM id for the main widgets. With this one click away can work well.

fix(extension): click away listener

---

extension/src/prototypes/ui-components/EntityTitle.tsx
extension/src/prototypes/ui-components/EntityTitleButton.tsx
extension/src/prototypes/view/ui-containers/CensusDatasetListItem.tsx
extension/src/prototypes/view/ui-containers/DatasetAreaList.tsx
extension/src/prototypes/view/ui-containers/DatasetDialog.tsx
extension/src/prototypes/view/ui-containers/DatasetTypeList.tsx

This PR:
- Adds `title` to layers item so that user can get the full name with mouse hover. (Sometimes the name is too long to display but user want to check the full name). The items includes:
- Layers item.
- Search result item.
- Items under 検索 都道府県 カテゴリー
- Adds support of wrap for EntityTitle and used in DatasetDialog so that it can display the full name of the dataset.

refactor(extension): update UI of layer title & dataset dialog title

---

extension/src/shared/view/containers/InitialLayers.tsx

Initial layer should be called only once during the app life time. Currently some state update will trigger adding initial layer as well. I added a ref to make sure `initialize` can be called only once.

fix(extension): unexpectedly triggered adding initial layer

---

extension/src/prototypes/view/ui-containers/DatasetDialog.tsx

Since we have updated the primary title before there's no need to display the secondary title now, some info are duplicated. (Request from feedback)

fix(extension): remove secondary title from dataset dialog

---

extension/src/editor/containers/dataset/index.tsx

A small fix to default status page of dataset editor. Currently it shows empty page.

fix(extension): dataset editor status page as default

---

.github/workflows/build-tiles.yml
.github/workflows/ci-tiles.yml
.github/workflows/ci.yml
.github/workflows/deploy-tiles-dev.yml
.github/workflows/deploy-tiles-prod.yml
tiles/README.md

Because there are no CIs yet.
> [!NOTE]
> The workload is GCE (because it uses GPU) and therefore, can't be deployed like the Cloud Run easily.  Thus, "deploy" here means to build a Docker artifact.

feat: add CI for PLATEAU View Tiles

---

extension/src/editor/containers/common/fieldComponentEditor/fields/general/EditorTimelineMonthField.tsx
extension/src/shared/ui-components/TimelineParameterItem.tsx
extension/src/shared/view/fields/general/LayerTimelineCustomizedField.tsx

This PR refactor the `TimelineParameterItem` to support set speed by amount and unit independently.

refactor(extension): support set speed amount and unit independently for timeline component

---

extension/src/editor/containers/dataset/FeatureInspectorPage.tsx
extension/src/editor/containers/dataset/blocks/FeatureInspectorEmphasisPropertyBlock.tsx
extension/src/editor/containers/dataset/index.tsx
extension/src/shared/view-layers/rootLayer.ts

This PR did some refactor on logic around default template matching for both emphasis property template and field component template. Also added a match info on editor.

refactor(extension): default template for emphasis property template

---

extension/src/prototypes/view/ui-containers/DatasetAreaList.tsx
extension/src/prototypes/view/ui-containers/DatasetTypeList.tsx

There're some datasets (almost all use case i guess) only have prefecture code but no city code, therefore they can't be displayed in area list and type list.
This PR adds query for these datasets and display them below the normal MunicipalityItems.

refactor(extension): support display datasets who has prefecture but no city in area list and type list

---

extension/src/editor/containers/common/fieldComponentEditor/fields/general/EditorPrioritizePerformanceGeoJSONField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/shared/layerContainers/hooks/useEvaluateGeneralData.ts
extension/src/shared/types/fieldComponents/general.ts
extension/src/shared/view/fields/fieldSettings.ts

This PR adds a new field component `EditorPrioritizePerformanceGeoJSONField` to set `data.geojson.useAsResource`
Test with dataset `都市活動/交通情報`

feat(extension): support load geojson as resource

---

extension/src/prototypes/view/ui-containers/DefaultDatasetSelect.tsx
extension/src/prototypes/view/ui-containers/LocationBreadcrumbItem.tsx

There's some mistake in filtering exist layers on location bread crumb select item, this PR fixs by filtering with dataset id. This should also work with layers added from search result.

fix(extension): location bread crumb items count

---

extension/src/editor/containers/common/fieldComponentEditor/fields/general/EditorOpacityField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/general/EditorStyleCodeField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/general/EditorTimelineCustomizedField.tsx
extension/src/editor/containers/ui-components/property/PropertySelectField.tsx
extension/src/prototypes/view/selection/TileFeatureContent.tsx
extension/src/prototypes/view/selection/TileFeaturePropertiesSection.tsx
extension/src/shared/layerContainers/buildingModel.tsx
extension/src/shared/layerContainers/floodModel.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/layerContainers/utils/value.ts
extension/src/shared/ui-components/TimelineParameterItem.tsx
extension/src/shared/view/fields/general/LayerOpacityField.tsx
extension/src/shared/view/fields/general/LayerStyleCodeField.tsx
extension/src/shared/view/fields/general/LayerTimelineCustomizedField.tsx
extension/src/shared/view/selection/GeneralFeaturePropertiesSection.tsx

This PR refactors some on:
- Support set default unit & value for custom timeline component.
Test with 菊池川時系列浸水シミュレーション（想定最大規模）/浸水シミュレーション(玉名駅周辺最大水深)
- Support set default opacity value from editor.
- Style code test with 建物利用現況（千種区）
- Building test with 建築物モデル（千代田区）LOD1
- Flood test with 高潮浸水想定区域モデル 東京都高潮浸水想定（平成30年3月）（千代田区）
- General test with 避難施設情報（中央区） Group Point Color Condition
- Add select layer button on tile select content

refactor(extension): custom timeline & transparency & style code component 

---

extension/src/prototypes/ui-components/EntityTitleButton.tsx
extension/src/prototypes/ui-components/SearchAutocomplete.tsx
extension/src/prototypes/view/hooks/useSearchOptions.ts
extension/src/prototypes/view/ui-containers/SearchList.tsx

This PR refactors the UI style for search result item. Set the location as secondary title to follow the original design language.

refactor(extension): set location as secondary title in search result

---

terraform/gcp/reearth.tf
terraform/gcp/reearth_cms.tf

Because the values were not passed even though the CMS module has a API:
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/blob/4cfeac732fbee33edff0c4a53306dcd0a13be0e8/terraform/gcp/modules/reearth_cms/variables.tf#L46-L50
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/blob/ead5e6727e4721485bd1dc89bf49285fde641c07/terraform/gcp/modules/reearth/variables.tf#L35-L39

fix: propagate GCP region to Re:Earth and CMS Terraform modules

---

extension/src/prototypes/ui-components/AppOverlayLayout.tsx
extension/src/prototypes/view/ui-containers/DatasetAreaList.tsx
extension/src/prototypes/view/ui-containers/DatasetTypeList.tsx
extension/src/prototypes/view/ui-containers/DefaultDatasetSelect.tsx
extension/src/prototypes/view/ui-containers/SearchList.tsx

This PR:
- sets the max height to 75% of the main height for search panel.
- always show select items for `fld` in location bread crumb popup.

refactor: max height of search panel on mobile

---

extension/src/index.ts
extension/src/prototypes/ui-components/AppOverlayLayout.tsx

Embedding CSS files improves portability of JS files, simplifies deployment, and prevents problems in advance.

chore(extension): embed overlayscrollbars css

---

extension/src/prototypes/screen-space-selection/ScreenSpaceSelection.tsx
extension/src/prototypes/screen-space-selection/ScreenSpaceSelectionEvent.ts
extension/src/prototypes/screen-space-selection/ScreenSpaceSelectionHandler.ts
extension/src/prototypes/view/containers/ScreenSpaceSelection.tsx
extension/src/shared/reearth/layers/index.ts
extension/src/shared/reearth/types/event.ts

Need: https://github.com/reearth/reearth/pull/932
I added support a feature to keep selecting the layer's feature with shift key. 
- In select mode, you can keep selecting the layer's feature with shift key.

feat(extension): select feature with shift

---

extension/src/shared/view/containers/InitialLayers.tsx
extension/src/shared/view/state/app.ts

This PR makes the layer initialized as a global state and avoid trigger duplication initialize (which could leading to add duplicate pedestrian layer).

fix(extention): duplicated pedestrian layer

---

extension/src/prototypes/ui-components/Inspector.tsx
extension/src/prototypes/view/ui-containers/EnvironmentSelect.tsx

Hide this button on mobile:
Also fix a small issue that forwarded `maxWidth` prop on a DOM element which leading to error msg throw out.

refactor(extension): hide elevation legend button on mobile

---

extension/src/prototypes/view/ui-containers/DefaultDatasetSelect.tsx
extension/src/prototypes/view/ui-containers/LocationBreadcrumbItem.tsx
extension/src/shared/plateau/constants.ts
extension/src/shared/plateau/index.ts

Hammatsu city has some ward, but these are merged into one ward in this year. However the digital government data which is used to find the city from ward in geo API is still not updated. So we need to use workaround for this part to show the several building model's data for wards only in Hamamatsu city.
- Search `浜松市`, and select something data, and move the camera for the data.
- Then layer shortcut should show some dataset for building model as list like flood model.

fix(extension): show building model for Hamamatsu city

---

extension/src/shared/graphql/hooks/catalog/datasetType.ts

This PR fixes the order shifting with using the initial type data and ignore the later data.

fix(extension): order shifting on type list

---

extension/src/prototypes/view/ui-containers/DatasetTreeSelect.tsx

Folder description dataset was not properly excluded when generate short cut menu.

fix(extension): exclude folder description dataset on short cut menu

---

extension/src/shared/reearth/layers/polygon.ts
extension/src/shared/view/containers/JapanPlateauPolygon.tsx

We were getting two performance issue.
1. Camera moving is slow
2. Evaluation is slow
There were two cause.
1. JapanPlateauPolygon is loaded always, therefore ton of features are in memory.
2. The polygon's appearance has `expression` property, so the ton of features are evaluated unnecessarily.

perf(extension): improve performance of Japan polygon

---

extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetApplyEmptySHCField.tsx
extension/src/editor/containers/common/fieldComponentEditor/fields/index.ts
extension/src/shared/layerContainers/buildingModel.tsx
extension/src/shared/layerContainers/floodModel.tsx
extension/src/shared/layerContainers/hooks/useEvaluateGeneralAppearance.ts
extension/src/shared/types/fieldComponents/3dtiles.ts
extension/src/shared/view/fields/fieldSettings.ts

This PR adds a new field component to set sphericalHarmonicCoefficients to `[]` on 3dtiles.
Test with dataset `ストーリーテリング型GISを用いたエリアマネジメントの高度化/作成した3D都市モデル/高輪ゲートウェイシティ 1街区（港区）`

feat(extension): add component to apply empty sphericalHarmonicCoefficients

---

extension/src/shared/ui-components/common/ViewMarkdownViewer.tsx
extension/src/shared/view/fields/general/LayerDatasetStoryField.tsx
extension/src/shared/view/fields/general/LayerLayerDescriptionField.tsx
extension/src/shared/view/selection/LegendDescriptionSection.tsx

This PR refactors the link component for markdown to open links in new tab.

refactor(extension): open markdown link in new tab

---

extension/src/prototypes/pedestrian/StreetViewFrustum.tsx

The frustum color looks a little bit darker than prototype since View 3.0 project doesn't hide underground by default. We need to change the color manually to make it looks more close to prototype's appearance.
| Before | After |
| -- | -- |
|![WX20240402-173711](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/21994748/b0bae017-0ed3-4f82-8601-4247d47a9b00) |![WX20240402-173635](https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/assets/21994748/57b71e89-1577-40f3-bab8-367c13deb913) |

refactor(extension): update frustum color

---

extension/src/editor/containers/common/fieldComponentEditor/fields/3dtiles/EditorTilesetBuildingModelColorField.tsx
extension/src/prototypes/view/selection/BuildingLayerColorSection.tsx
extension/src/shared/layerContainers/buildingModel.tsx
extension/src/shared/plateau/layers/TilesetProperties.ts
extension/src/shared/types/fieldComponents/3dtiles.ts
extension/src/shared/view-layers/component.ts
extension/src/shared/view-layers/rootLayer.ts
extension/src/shared/view/selection/ColorSchemeSectionForComponentField.tsx
extension/src/shared/view/selection/ImageSchemaSectionForComponentField.tsx

I updated the TilesetBuildingModelColorField to be able to override the hard-coded property's color by JSON. For this requirement, we might get additional requirement, and it's impossible to support all of requirement as UI, so we decided to use JSON.
You can test it by using `TEST-kya/OVERRIDE_COLOR_SET` template and using `建築物モデル（沼津市）`. And you need to re-add the dataset after you applied the component.
The format is like below.
```
{
// First matched value is used to override the colorSet.
"overrides": [
{
"propertyName": "津波浸水想定区域モデル 静岡県第４次地震被害想定（元禄型関東地震）", // REQUIRED
"matcher": "startsWith", // OPTIONAL: `startsWith` or `endsWith` (default is `equal`)
"colorSet": [ // REQUIRED
{
"value": 6,
"color": "#FF0000",
"name": "6"
},
{
"value": 5,
"color": "#00FF00",
"name": "5"
},
{ …
```

fix(extension): override building model color

---

extension/src/shared/view/containers/JapanPlateauPolygon.tsx

Japan polygon is yellow sometimes when I continue to zoom-in and out to show the polygon. The cause seems that the the style of polygon isn't applied by Cesium when the big polygon is re-loaded(removed and created) frequently(I don't known why...). So I fixed to update `show` property which is defined in some appearance to show the polygon without re-loading. The polygon is too big, so I did to use `show` property only if the polygon is loaded at least once.

fix(extension): use show property to toggle Japan polygon

---

extension/src/editor/containers/common/fieldComponentEditor/fields/general/EditorTimelineCustomizedField.tsx
extension/src/shared/reearth/hooks/useTimeline.ts
extension/src/shared/ui-components/TimelineParameterItem.tsx
extension/src/shared/view/fields/general/LayerTimelineCustomizedField.tsx
extension/src/shared/view/fields/general/LayerTimelineMonthField.tsx

This PR adds these support on timeline component:
- Switch play mode between play once and loop (default).
- Set time display type as current or past for customized timeline component. When it's past editor can setup a format for the text. Support `HH` `mm` `ss` only.
You can test by searching datasets with `時系列` in name. (prod API)

feat(extension): support loop and display past time in timeline component

---

extension/reearth-yml.ts
extension/src/editor/containers/component-template/index.tsx
extension/src/editor/containers/dataset/blocks/FeatureInspectorEmphasisPropertyBlock.tsx
extension/src/editor/containers/dataset/blocks/FieldComponentTemplateBlock.tsx
extension/src/editor/containers/dataset/index.tsx
extension/src/editor/containers/emphasis-property-template/index.tsx
extension/src/shared/api/clients/base.ts
extension/src/shared/api/clients/setting.ts
extension/src/shared/api/clients/template.ts
extension/src/shared/api/hooks/settings.ts
extension/src/shared/api/hooks/template.ts
extension/src/shared/context/WidgetContext.tsx
extension/src/shared/states/environmentVariables.ts
extension/src/shared/view/containers/InitialLayers.tsx
extension/src/toolbar/Widget.tsx

In city project, we need to use the component which is set up in VIEW3.0 project, but city project's component API return just the component for city project. So we need to fetch the component for VIEW3.0 and city project.
The specification of city project is below.
1. Use VIEW3.0's component and template for VIEW3.0's dataset.
2. Edit the component and template only for city project's dataset.
3. We don't allow to show and edit the component and template for VIEW3.0 in city project.

fix(extension): use component from PLATEAU in city project

---

.github/workflows/deploy-cms-dev.yml
.github/workflows/deploy-cms-prod.yml
.github/workflows/deploy-geo-dev.yml
.github/workflows/deploy-geo-prod.yml
.github/workflows/deploy-reearth-dev.yml
.github/workflows/deploy-reearth-prod.yml
.github/workflows/deploy-server-dev.yml
.github/workflows/deploy-server-prod.yml
.github/workflows/deploy-tiles-dev.yml
.github/workflows/deploy-tiles-prod.yml
.github/workflows/deploy-worker-dev.yml
.github/workflows/deploy-worker-prod.yml

Because the GCR (Google Container Registry) will be decommissioned.
Note that production and development environment refers to the images on GitHub registry so they can be migrated step by step. 
* [Transition from Container Registry, Google Cloud](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr) 
> Container Registry is deprecated and scheduled for shutdown. After May 15, 2024, Artifact Registry will host images for the gcr.io domain in Google Cloud projects without previous Container Registry usage

ci: migrate to GAR from GCR

---

extension/src/editor/containers/dataset/index.tsx
extension/src/shared/api/clients/base.ts
extension/src/shared/api/clients/setting.ts
extension/src/shared/api/clients/template.ts
extension/src/shared/context/WidgetContext.tsx

I fixed two things.
1. Allow token be optional property.
2. Show a message about PLATEAU dataset isn't editable in the city project.

fix(extension): allow optional token and show a message about PLATEAU dataset isn't editable

---

extension/src/editor/containers/dataset/GeneralPage.tsx
extension/src/editor/containers/dataset/index.tsx
extension/src/editor/containers/ui-components/editor/EditorTreeItem.tsx
extension/src/editor/hooks/useIsCityOrPlateauDataset.ts
extension/src/shared/api/hooks/settings.ts
extension/src/shared/states/setting.ts
extension/src/shared/view/containers/InitialLayers.tsx
extension/src/toolbar/containers/InitializeApp.tsx

I fixed the editor to allow overridding an `Initial layer` field for PLATEAU dataset in a city project.
This only allows `Initial layer` field, but other fields aren't allowed.

fix(extension): allow editing an initial layer field for PLATEAU dataset in a city project

---

extension/src/prototypes/view/containers/Environments.tsx
extension/src/shared/reearth/types/scene.ts

Hide a tile label if camera pitch is under the specific degree.
ReEarth Core: https://github.com/reearth/core/pull/48
https://github.com/user-attachments/assets/07223cde-3b81-40a4-809e-78154fc4712c

fix(extension): add a distance condition for tile label

---

server/citygml/packer.go

This update introduces a check to ensure the URL list is not empty, returning a BadRequest error if no URLs are provided. Additionally, a missing step name "citygml-pack" is added for clarity in build steps. These modifications enhance the robustness and readability of the citygml packer process.

fix(server): Add validation for empty URL list in citygml packer

---

server/citygml/echo.go

Change route parameters from `{}` to `:` in endpoint paths to follow Echo's conventions. Added `.zip` suffix validation for `GET /pack/:id.zip` endpoint to handle invalid requests.

fix(server): Fix route parameters in citygml echo server

---

.github/workflows/deploy-cms-dev.yml
.github/workflows/deploy-cms-prod.yml

We have already migrated to Cloud Run already so it's not used anymore.
For example:
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/blob/a9cfc2ae85017677f4b15cff80ac4a7ba0e18713/.github/workflows/deploy-cms-dev.yml#L19-L60

ci: remove Re:Earth CMS web GCS deploy workflow

---

extension/reearth-yml.ts
extension/src/prototypes/view/selection/SpatialIdObjectContent.tsx
extension/src/shared/api/citygml/client.ts
extension/src/shared/api/citygml/index.ts
extension/src/shared/api/citygml/types.ts
extension/src/shared/context/WidgetContext.tsx
extension/src/shared/states/environmentVariables.ts
extension/src/toolbar/Widget.tsx

This PR added one single cityGML api for fetch the files by space id, and show the data on spatial id object's selection panel.
Note: there's a new widget property on Toolbar, `cityGMLURL`, please enter this url: `https://api.plateauview.mlit.go.jp/datacatalog/citygml`
- Didn't implement all the cityGML apis.
- The UI on spatial id object's selection needs re-design, current one is temporary.

feat(extension): add cityGML api & update selection content for spatial id object

---

.github/workflows/deploy-reearth-visualizer-dev.yml

We've already migrated to Cloud Run but this workflow was still deploying our frontend to the GCS bucket.
https://github.com/eukarya-inc/PLATEAU-VIEW-3.0/actions/runs/12783773476

ci: migrate Visualizer frontend workflow to Cloud Run

---

extension/src/prototypes/view/selection/LayerMeshCodeSection.tsx
extension/src/prototypes/view/selection/MeshCodeObjectContent.tsx
extension/src/prototypes/view/selection/SpatialIdObjectContent.tsx
extension/src/prototypes/view/states/tool.ts
extension/src/shared/meshCode/MeshCodeDrawer.tsx
extension/src/shared/reearth/layers/meshCodeIndicator.ts

This PR fixes the useAtomValue for mesh code layer feature and spatial id layer feature.
Also:
- update the indicator style for mesh code layer.
- set default mesh code level to 3.
- remove the setTimeout of select new created mesh code object.

fix(extension): useAtomValue with undefined

---

.github/workflows/deploy-cms-dev.yml
.github/workflows/deploy-cms-prod.yml
.github/workflows/deploy-extension-dev.yml
.github/workflows/deploy-extension-prod.yml
.github/workflows/deploy-geo-dev.yml
.github/workflows/deploy-geo-prod.yml
.github/workflows/deploy-reearth-classic-dev.yml
.github/workflows/deploy-reearth-classic-prod.yml
.github/workflows/deploy-reearth-flow-dev.yml
.github/workflows/deploy-reearth-flow-prod.yml
.github/workflows/deploy-reearth-visualizer-dev.yml
.github/workflows/deploy-reearth-visualizer-prod.yml
.github/workflows/deploy-server-dev.yml
.github/workflows/deploy-server-prod.yml
.github/workflows/deploy-tiles-dev.yml
.github/workflows/deploy-tiles-prod.yml
.github/workflows/deploy-worker-dev.yml
.github/workflows/deploy-worker-prod.yml

Already migrated to Cloud Run and we don't need to run `setup-gcloud`, the `auth` action will do it for us.

ci: remove GCS upload job and unnecessary `gcloud` setup

---

extension/src/shared/reearth/layers/mvt.ts

I fixed to allow loading MVT without metadata.json, since the selected data doesn't include it.

fix: allow loading MVT without metadata
